(define (frames avatar-path output-path)
  (define img (vector-ref (cadr (gimp-image-list)) 0))
  (define layer (car (gimp-file-load-layer 0 img avatar-path)))
  (gimp-image-insert-layer img layer 0 -1)
  (gimp-layer-scale layer 910 630 1)
  (define mask (car (gimp-layer-create-mask layer 1)))
  (gimp-layer-add-mask layer mask)
  (gimp-layer-set-offsets layer 114 114)
  (gimp-context-set-foreground '(255 255 255))
  (gimp-edit-bucket-fill mask 0 0 100 0 1 75 75)
  (gimp-image-merge-visible-layers img CLIP-TO-BOTTOM-LAYER)
(gimp-file-save 1 img (car (gimp-image-get-active-layer img)) output-path ""))
